-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 21:20:02 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cowlib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cowlib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cowlib` DEFAULT CHARACTER SET utf8 ;
USE `cowlib` ;

-- -----------------------------------------------------
-- Table `cowlib`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cowlib`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(45) NULL,
  `isbn13` VARCHAR(45) NULL,
  `title` VARCHAR(128) NULL,
  `author` VARCHAR(45) NULL,
  `description` VARCHAR(2048) NULL,
  `publisher` VARCHAR(45) NULL,
  `cover_url` VARCHAR(2048) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cowlib`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cowlib`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `facebook_id` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(2048) NULL,
  `name` VARCHAR(45) NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cowlib`.`call_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cowlib`.`call_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_book_book1_idx` (`book_id` ASC),
  INDEX `fk_user_has_book_user_idx` (`owner_id` ASC),
  CONSTRAINT `fk_user_has_book_user`
    FOREIGN KEY (`owner_id`)
    REFERENCES `cowlib`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `cowlib`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cowlib`.`borrow_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cowlib`.`borrow_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `call_number_id` INT NOT NULL,
  `borrower_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `last_modifed_dttm` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_borrow_history_user_has_book1`
    FOREIGN KEY (`call_number_id`)
    REFERENCES `cowlib`.`call_number` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cowlib`.`wait_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cowlib`.`wait_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `call_number_id` INT NOT NULL,
  `waiter_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `last_modifed_dttm` TIMESTAMP NULL,
  INDEX `fk_waiter_history_user_has_book1_idx` (`call_number_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_waiter_history_user_has_book1`
    FOREIGN KEY (`call_number_id`)
    REFERENCES `cowlib`.`call_number` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cowlib`.`bookmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cowlib`.`bookmark` (
  `user_id` INT NOT NULL,
  `bookmark` INT NOT NULL,
  `is_deleted` TINYINT(1) NULL,
  INDEX `fk_bookmark_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`, `bookmark`),
  CONSTRAINT `fk_bookmark_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cowlib`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
